++helm upgrade nowait + resource version check

diff --git a/actions/k8s-deploy/action.yaml b/actions/k8s-deploy/action.yaml
--- a/actions/k8s-deploy/action.yaml
+++ b/actions/k8s-deploy/action.yaml
@@ -8,13 +8,8 @@ inputs:
     type: string
   timeout_seconds:
     description: 'Kubectl apply wait timeout in seconds for Deployments'
-    required: true
+    required: false
     type: number
-  force_restart:
-    description: 'Force Deployment Rollout Restart'
-    required: true
-    default: false
-    type: boolean
   kind:
     description: 'Kind of resource to deploy (microservice or cronjob)'
     required: true
@@ -32,6 +27,11 @@ inputs:
     type: string
   helm_force_upgrade:
     description: 'Enable Helm force upgrade option'
+    required: false
+    default: false
+    type: boolean
+  helm_upgrade_no_wait:
+    description: 'Do not wait for Helm upgrade to finish'
     required: false
     default: false
     type: boolean
@@ -129,7 +129,7 @@ runs:
 
         if [[ "${{ env.microservice_defined }}" == "true" ]]; then
           set +e
-          if [[ "${{inputs.use_kubectl_diff}}" == "true" ]]; then
+          if [[ "${{ inputs.use_kubectl_diff }}" == "true" ]]; then
             $SCRIPTS_FOLDER/kubectlDiff-svc-single-standalone.sh --skip-dep --environment ${{ inputs.environment }} --microservice ${{ inputs.target }} -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml --output console
           else
             $SCRIPTS_FOLDER/helmDiff-svc-single-standalone.sh --skip-dep --environment ${{ inputs.environment }} --microservice ${{ inputs.target }} -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml
@@ -166,25 +166,39 @@ runs:
         
         if [[ "${{ env.microservice_defined}}" != "true" && "${{ env.cronjob_defined }}" != "true" ]]; then
           echo "::error::Neither microservice nor cronjob is defined."
-          exit $DIFF_EXIT_CODE
+          exit 1
         fi
 
-        TIMEOUT="${{ inputs.timeout_seconds }}s"
+        TIMEOUT_OPT=""
+        NOWAIT_OPT=""
+
+        if [[ -n "${{ inputs.timeout_seconds }}" ]]; then
+          if [[ "${{ inputs.helm_upgrade_no_wait }}" == "true" ]]; then
+            echo "::warning::INFO - Helm upgrade will not wait for the deployment to finish."
+            NOWAIT_OPT="--no-wait"
+          else
+            echo "::warning::INFO - Helm upgrade will wait for the deployment to finish."
+            TIMEOUT_OPT="--timeout ${{ inputs.timeout_seconds }}s"
+          fi
+        fi
 
         export PROJECT_DIR=$(pwd)
 
         if [[ "${{ env.microservice_defined }}" == "true" ]]; then
-          $SCRIPTS_FOLDER/helmTemplate-svc-single.sh --debug -e ${{ inputs.environment }} -m "${{ inputs.target }}" -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml --output console > template.yaml
+          $SCRIPTS_FOLDER/helmTemplate-svc-single.sh --debug --environment ${{ inputs.environment }} -m "${{ inputs.target }}" -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml --output console > template.yaml
 
           K8S_NAMESPACE=$(cat template.yaml | yq 'select(.kind == "Deployment") | .metadata.namespace')
           MICROSERVICE_FULLNAME=$(cat template.yaml | yq 'select(.kind == "Deployment") | .metadata.name')
           
+          # Get deployment resourceVersion current value
+          CURRENT_RESOURCE_VERSION=$(kubectl get deployment "$MICROSERVICE_FULLNAME" -n "$K8S_NAMESPACE" -o jsonpath='{.metadata.resourceVersion}') 
+          
           echo "INFO - Apply changes for $MICROSERVICE_FULLNAME."
-          if [[ ${{inputs.use_kubectl_apply}} == "true" ]]; then
+          if [[ "${{ inputs.use_kubectl_apply }}" == "true" ]]; then
             "$SCRIPTS_FOLDER/kubectlApply-svc-single-standalone.sh" --debug --skip-dep --environment "$K8S_NAMESPACE" -m "${{ inputs.target }}" -i $PROJECT_DIR/commons/$K8S_NAMESPACE/images.yaml --output console
           
           else
-            HELM_UPGRADE_OPTIONS="--debug --skip-dep --output console"
+            HELM_UPGRADE_OPTIONS="--debug --skip-dep $TIMEOUT_OPT $NOWAIT_OPT --output console"
 
             if [[ "${{ inputs.helm_force_upgrade }}" == "true" ]]; then
               echo "::warning::INFO - Helm force upgrade requested for $MICROSERVICE_FULLNAME."
@@ -194,34 +208,35 @@ runs:
             "$SCRIPTS_FOLDER/helmUpgrade-svc-single-standalone.sh" $HELM_UPGRADE_OPTIONS --environment "$K8S_NAMESPACE" -m "${{ inputs.target }}" -i $PROJECT_DIR/commons/$K8S_NAMESPACE/images.yaml
           fi
 
-          DESIRED_REPLICAS=$(kubectl get deployment "$MICROSERVICE_FULLNAME" -n "$K8S_NAMESPACE" -o jsonpath='{.spec.replicas}')
-          echo "INFO - Desired replicas: $DESIRED_REPLICAS"
-          if [ "$DESIRED_REPLICAS" -eq 0 ]; then
-            echo "::info::INFO - Desired replicas for $MICROSERVICE_FULLNAME are 0. Stopping further operations."
-            exit 0
-          fi
+          # Deployment resourceVersion should be updated after the apply or upgrade if successfully executed (always updated when helm upgrade is forced)
+          POLL_INTERVAL=5
+          start_time=$(date +%s)
+          
+          while true; do
+            UPDATED_RESOURCE_VERSION=$(kubectl get deploy "${MICROSERVICE_FULLNAME}" -n "${K8S_NAMESPACE}" -o jsonpath='{.metadata.resourceVersion}')
 
-          # Check if the force rollout flag is true
-          if [ "${{ inputs.force_restart }}" = true ]; then
-            echo "::info::INFO - Force rollout restart requested $MICROSERVICE_FULLNAME."
-            if ! kubectl rollout status -n "$K8S_NAMESPACE" "deployment/$MICROSERVICE_FULLNAME" --watch=false >/dev/null 2>&1; then
-              echo "::info::INFO - Rollout already active for $MICROSERVICE_FULLNAME. No force restart needed."
+            if [[ "${UPDATED_RESOURCE_VERSION}" == "${CURRENT_RESOURCE_VERSION}" ]]; then
+              echo "Resource version has not yet changed"
             else
-              echo "INFO - No rollout in progress, forcing a rollout restart."
-              kubectl rollout restart -n "$K8S_NAMESPACE" "deployment/$MICROSERVICE_FULLNAME"
+              echo "Resource version has changed from ${CURRENT_RESOURCE_VERSION} to ${UPDATED_RESOURCE_VERSION}"
+              break
             fi
-          fi
 
-          echo "INFO - Wait for the rollout of the $MICROSERVICE_FULLNAME to finish (Max $TIMEOUT)."
-          if ! kubectl rollout status -n "$K8S_NAMESPACE" "deployment/$MICROSERVICE_FULLNAME" --timeout="$TIMEOUT" --watch >/dev/null 2>&1; then
-            echo "::error::ERROR - Rollout for $MICROSERVICE_FULLNAME failed or exceeded $TIMEOUT."
-            exit 1
-          fi
+            current_time=$(date +%s)
+            elapsed=$(( current_time - start_time ))
+            # Check if the elapsed time exceeds the timeout (prevent infinite loop if no diff is found but helm upgrade is executed)
+            if (( elapsed > "${{ inputs.timeout_seconds }}" )); then
+              echo "::error:: Timeout after ${{ inputs.timeout_seconds }}s waiting for ${MICROSERVICE_FULLNAME} deploy."
+              exit 1
+            fi
 
-          echo "INFO - Rollout for $MICROSERVICE_FULLNAME completed successfully."
+            sleep $POLL_INTERVAL
+          done
+
+          echo "INFO - Deploy for $MICROSERVICE_FULLNAME completed successfully."
         
         elif [[ "${{ env.cronjob_defined }}" == "true" ]]; then
-          $SCRIPTS_FOLDER/helmTemplate-cron-single.sh --debug -e ${{ inputs.environment }} --job "${{ inputs.target }}" -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml --output console > template.yaml
+          $SCRIPTS_FOLDER/helmTemplate-cron-single.sh --debug --environment ${{ inputs.environment }} --job "${{ inputs.target }}" -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml --output console > template.yaml
         
           K8S_NAMESPACE=$(cat template.yaml | yq 'select(.kind == "CronJob") | .metadata.namespace')
           CRONJOB_FULLNAME=$(cat template.yaml | yq 'select(.kind == "CronJob") | .metadata.name')
