add helm chart validation

diff --git a/.github/workflows/common-deployment-values-validation.yaml b/.github/workflows/common-deployment-values-validation.yaml
--- a/.github/workflows/common-deployment-values-validation.yaml
+++ b/.github/workflows/common-deployment-values-validation.yaml
@@ -24,6 +24,49 @@ env:
   SCRIPTS_FOLDER: "./interop-infra-commons/scripts/helm"
 
 jobs:
+  chart_validation:
+    name: Helm Chart validation
+    runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        chartType: ["microservice", "cronjob"]
+      fail-fast: false
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
+      
+      - name: Checkout scripts repository
+        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
+        with:
+          repository: pagopa/interop-infra-commons
+          path: interop-infra-commons
+          fetch-depth: 0
+          sparse-checkout: 'scripts/helm'
+          ref: ${{ inputs.infra_commons_tag }}
+      
+      - name: Helm Chart Linting
+        id: helm_lint
+        env:
+          CHART_TYPE: ${{ matrix.chartType }}
+          ENVIRONMENT: ${{ inputs.environment }}
+        run: |
+          set -euo pipefail
+
+          OPTIONS=""
+
+          if [[ $CHART_TYPE == "microservice" ]]; then
+            OPTIONS=" --microservices "
+          elif [[ $CHART_TYPE == "cronjob" ]]; then
+            OPTIONS=" --jobs "
+          else
+            echo "::error:: Workflow cannot be run on selected chart $CHART_TYPE"
+            exit 1
+          fi
+
+          export PROJECT_DIR=$(pwd)
+
+          $SCRIPTS_FOLDER/helmLint-main.sh --debug --environment "$ENVIRONMENT" --output console $OPTIONS -i $PROJECT_DIR/commons/"$ENVIRONMENT"/images.yaml
 
   microservices_validation:
     name: Microservices - Template & Lint
